In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [3]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
df=pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [6]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

## Dependent and independent features

In [7]:
x=df
y=dataset.target

In [8]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
## for binary logistic regression, from target feature lets select only two variable

In [11]:
df['target']=dataset.target

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
df_new=df[df['target']!=2]

In [14]:
df_new.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [15]:
## now we are taking dependent and independent features for binary classification.

In [16]:
x=df_new.iloc[:,:-1]
y=df_new.iloc[:,-1]

In [17]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
# Train test split
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.20, random_state=42)

In [22]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [23]:
## For training data 

In [24]:
obj_logistic=LogisticRegression()

In [25]:
obj_logistic.fit(x_train, y_train)

LogisticRegression()

In [26]:
## for predication

In [27]:
y_predict=obj_logistic.predict(x_test)

In [28]:
y_predict

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [29]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [30]:
## confusion matrix, accuracy score, classification report

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [32]:
# print(confusion_matrix(y_predict, y_test))
# print(accuracy_score(y_predict, y_test))
print(classification_report(y_predict, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Hyperperameter tuning

In [33]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [34]:
paremeters={'penalty':('l1','l2','elasticnet',None),'C':[1,2,20]}

In [36]:
clf=GridSearchCV(obj_logistic, param_grid=paremeters, cv=5)

In [37]:
## spliting of Train data to validation data
clf.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [38]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [39]:
obj_logistic= LogisticRegression(C=1, penalty='l2')

In [40]:
obj_logistic.fit(x_train, y_train)

LogisticRegression(C=1)

In [42]:
y_predict=obj_logistic.predict(x_test)
print(confusion_matrix(y_predict, y_test))
print(accuracy_score(y_predict, y_test))
print(classification_report(y_predict, y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [43]:
## Randomazied search cv

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [45]:
random_csf=RandomizedSearchCV(LogisticRegression(), param_distributions=paremeters, cv=5)

In [46]:
random_csf.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [47]:
random_csf.best_params_

{'penalty': None, 'C': 1}

In [48]:
obj_logistic=LogisticRegression(C=1, penalty=None)

In [49]:
obj_logistic.fit(x_train, y_train)

LogisticRegression(C=1, penalty=None)

In [50]:
y_predict=obj_logistic.predict(x_test)
print(confusion_matrix(y_predict, y_test))
print(accuracy_score(y_predict, y_test))
print(classification_report(y_predict, y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

